version: "3"
services:
  frontend:
    container_name: frontend-container
    build: ./frontend-typescript
    volumes:
      - ../frontend:/workdir
    expose:
      - "4062"
    ports:
      - "4062:4062"
    tty: true

  backend:
    container_name: backend-container
    build: ./backend-python
    volumes:
      - ../backend:/workdir
    expose:
      - "6889"
    ports:
      - "6889:6889"
    tty: true

  database:
    container_name: database-container
    build: ./database-postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ../database/init:/docker-entrypoint-initdb.d
      - ../database/temp:/temp
      - pgdata:/var/lib/postgresql/data
    expose:
      - "4321"
    ports:
      - "4321:4321"
    environment:
      POSTGRES_PASSWORD: password1234
      TZ: "Asia/Tokyo"
    command: -p 4321

volumes:
  pgdata:
